# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0030_pgmismatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpofpg',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='PG', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MPOfPg_1', to='parlaskupine.Organization'),
        ),
    ]
