# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parlaposlanci', '0038_auto_20190329_1048'),
        ('parlaskupine', '0031_auto_20180820_1140'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='Compass',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, verbose_name='creation time', editable=False)),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, verbose_name='last modification time', editable=False)),
                ('calculated_from', models.DateField(help_text='date of first ballot entered', null=True, verbose_name='date of first ballot entered', blank=True)),
                ('created_for', models.DateField(help_text='date of activity', null=True, verbose_name='date of analize', blank=True)),
                ('data', jsonfield.fields.JSONField(null=True, blank=True)),
            ],
            options={
                'db_table': 'parlaskupine_compass',
            },
            bases=(models.Model,),
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
