# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0032_auto_20190329_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='compass',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Org', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Compass', to='parlaskupine.Organization'),
        ),
        migrations.AlterModelTable(
            name='compass',
            table=None,
        ),
    ]
