# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0033_auto_20190329_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_voters',
            field=models.BooleanField(default=True, help_text='Has organization voters?', verbose_name='has voters'),
        ),
    ]
