# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0034_organization_has_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='has_voters',
            field=models.BooleanField(default=False, help_text='Has organization voters?', verbose_name='has voters'),
        ),
    ]
