# -*- coding: utf-8 -*-
"""
Django settings for parlalize project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import raven

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'taggit',
    'djgeojson',
    'leaflet',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parlaposlanci',
    'parlaskupine',
    'parlaseje',
    'django_extensions',
    'raven.contrib.django.raven_compat',
    'corsheaders',
    'tinymce',
    'utils',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'parlalize.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parlalize.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'sl-si'

TIME_ZONE = 'Europe/Ljubljana'

USE_I18N = True

USE_L10N = True

USE_TZ = False


LAST_ACTIVITY_COUNT = 10


# PARLALIZE vote options represent for vote analyses
# in ballots we save the option as string. this is used to transform it to a numerical value
VOTE_MAP = {
    "za": 1, # for
    "proti": -1, # against
    "kvorum": 0, # abstain
    "ni": 0, # not present
    "ni_poslanec": 0 # is not a Member
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


API_DATE_FORMAT = '%d.%m.%Y'
API_OUT_DATE_FORMAT = '%-d. %-m. %Y'

# CORS config
CORS_ORIGIN_ALLOW_ALL = True

# Legislation status options: in procedure / procedure ended
# we use these in the django admin interface to define select dropdown options
# it is tied to the model, so if you change this please check parlaseje.models.Legislation
LEGISLATION_STATUS = [('v obravnavi', 'v obravnavi'), ('konec obravnave', 'konec obravnave')]

# Legislation result: empty / accepted / rejected
# we use these in the django admin interface to define select dropdown options
# it is tied to the model, so if you change this please check parlaseje.models.Legislation
LEGISLATION_RESULT = [(None, 'Prazno'), ('sprejet', 'sprejet'), ('zavrnjen', 'zavrnjen')]

# Vote classificators. Vote text contains. This is tied to VOTE_NAMES.
VOTE_INDICATORS = { 
    '1': ['dnevni red', 'širitev dnevnega reda', 'umik točke dnevnega reda'], 
    '2': ['glasovanje o zakonu v celoti'], 
    '3': ['amandma'], 
    '4': ['interpelacija'], 
    '5': ['evidenčni sklep'], 
    '6': ['predlog sklepa'], 
    '7': ['zakon o ratifikaciji'], 
    '8': ['sklep o imenovanju', 
          'predlog za imenovanje', 
          'izvolitev', 
          'soglasje k imenovanju', 
          'predlog kandidata', 
          'predlog kandidatke', 
          'sklep o izvolitvi', 
          'predlog za izvolitev'], 
    '9': ['predlog za razpis'], 
    '10': ['priporočilo'], 
    '11': ['poročilo'], 
    '12': ['proceduralni predlog'], 
    '13': ['odlok o načrtu ravnanja s stvarnim premoženjem'],
}

# Vote classification
VOTE_NAMES = { 
    '1': 'dnevni red', # agenda
    '2': 'glasovanje o zakonu v celoti', # final votiong 
    '3': 'amandma', # amendment
    '4': 'interpelacija', # interpelation
    '5': 'evidenčni sklep', # record conclusion
    '6': 'predlog sklepa', # proposal for a decision
    '7': 'zakon o ratifikaciji', # ratification law
    '8': 'imenovanje', # naming
    '9': 'predlog za razpis', # proposal for a call
    '10': 'priporočilo', # recommendation 
    '11': 'poročilo', # report 
    '12': 'proceduralni predlog', # procedural proposal 
    '13': 'odlok o načrtu ravnanja s stvarnim premoženjem',
    '14': 'drugo' # others
}

TINYMCE_INCLUDE_JQUERY = False