# -*- coding: utf-8 -*-
"""
Django settings for parlalize project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import raven

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'taggit',
    'djgeojson',
    'leaflet',
    'dal',
    'dal_select2',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parlaposlanci',
    'parlaskupine',
    'parlaseje',
    'django_extensions',
    'raven.contrib.django.raven_compat',
    'corsheaders',
    'tinymce',
    'utils',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'parlalize.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parlalize.wsgi.application'


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'sl-si'

TIME_ZONE = 'Europe/Ljubljana'

USE_I18N = True

USE_L10N = True

USE_TZ = False


LAST_ACTIVITY_COUNT = 10


#PARLALIZE votes represent
VOTE_MAP = {
    "za": 1,
    "proti": -1,
    "kvorum": 0,
    "ni": 0,
    "ni_poslanec": 0
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


API_DATE_FORMAT = '%d.%m.%Y'
API_OUT_DATE_FORMAT = '%-d. %-m. %Y'

# CORS config
CORS_ORIGIN_ALLOW_ALL = True

LEGISLATION_STATUS = [('v obravnavi', 'v obravnavi'), ('konec obravnave', 'konec obravnave')]

LEGISLATION_RESULT = [(None, 'Prazno'), ('sprejet', 'sprejet'), ('zavrnjen', 'zavrnjen')]

VOTE_INDICATORS = { 
    '1': ['dnevni red', 'širitev dnevnega reda', 'umik točke dnevnega reda'], 
    '2': ['glasovanje o zakonu v celoti'], 
    '3': ['amandma'], 
    '4': ['interpelacija'], 
    '5': ['evidenčni sklep'], 
    '6': ['predlog sklepa'], 
    '7': ['zakon o ratifikaciji'], 
    '8': ['sklep o imenovanju', 
          'predlog za imenovanje', 
          'izvolitev', 
          'soglasje k imenovanju', 
          'predlog kandidata', 
          'predlog kandidatke', 
          'sklep o izvolitvi', 
          'predlog za izvolitev'], 
    '9': ['predlog za razpis'], 
    '10': ['priporočilo'], 
    '11': ['poročilo'], 
    '12': ['proceduralni predlog'], 
    '13': ['odlok o načrtu ravnanja s stvarnim premoženjem'],
}

VOTE_NAMES = { 
    '1': 'dnevni red',
    '2': 'glasovanje o zakonu v celoti', 
    '3': 'amandma', 
    '4': 'interpelacija', 
    '5': 'evidenčni sklep', 
    '6': 'predlog sklepa', 
    '7': 'zakon o ratifikaciji', 
    '8': 'imenovanje',
    '9': 'predlog za razpis', 
    '10': 'priporočilo', 
    '11': 'poročilo', 
    '12': 'proceduralni predlog',
    '13': 'odlok o načrtu ravnanja s stvarnim premoženjem',
    '14': 'drugo'
}

TINYMCE_INCLUDE_JQUERY = False