# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0001_initial'),
        ('parlaposlanci', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberslist',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_list', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='ministerstatic',
            name='ministry',
            field=models.ForeignKey(blank=True, help_text='Parladata party id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ministry_ministers', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='ministerstatic',
            name='party',
            field=models.ForeignKey(blank=True, help_text='Parladata party id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_ministers', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='mpstaticpl',
            name='party',
            field=models.ForeignKey(help_text='Parladata party id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='static_party', to='parlaskupine.Organization'),
        ),
    ]
