# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaposlanci', '0035_mpstaticpl_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spokenwords',
            name='maxMP',
            field=models.ForeignKey(blank=True, help_text='Person who has max spoken words', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrenSW_1', to='parlaposlanci.Person'),
        ),
    ]
