# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlaposlanci', '0036_auto_20180820_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpstaticpl',
            name='points',
            field=models.IntegerField(blank=True, help_text='Number of points', null=True),
        ),
    ]
