# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-02 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0035_auto_20190402_2104'),
        ('parlaposlanci', '0038_auto_20190329_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberslist',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members_list', to='parlaskupine.Organization'),
        ),
    ]
