# Generated by Django 1.11 on 2019-10-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaposlanci', '0002_auto_20191018_1503'),
        ('parlaskupine', '0001_initial'),
        ('parlaseje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ManyToManyField(blank=True, help_text='MP', to='parlaposlanci.Person'),
        ),
        migrations.AddField(
            model_name='amendmentoforg',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parlaskupine.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ballot',
            name='org_voter',
            field=models.ForeignKey(blank=True, help_text='Organization voter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OrganizationVoter', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='ballot',
            name='voter_party',
            field=models.ForeignKey(blank=True, help_text='Party of voter', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ballotsOfVoters', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='author_org',
            field=models.ForeignKey(blank=True, help_text='Author organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuthorOrg', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='author_orgs',
            field=models.ManyToManyField(blank=True, help_text='Author organizations', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='recipient_organizations',
            field=models.ManyToManyField(blank=True, help_text=b"Recipient organizations (if it's an organization).", related_name='questions_org', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='recipient_persons',
            field=models.ManyToManyField(blank=True, help_text=b"Recipient persons (if it's a person).", related_name='questions', to='parlaposlanci.Person'),
        ),
        migrations.AddField(
            model_name='question',
            name='recipient_persons_static',
            field=models.ManyToManyField(blank=True, help_text=b"Recipient persons (if it's a person).", related_name='questions_static', to='parlaposlanci.MinisterStatic'),
        ),
        migrations.AddField(
            model_name='session',
            name='organization',
            field=models.ForeignKey(blank=True, help_text=b'The organization in session', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='session',
            name='organizations',
            field=models.ManyToManyField(help_text=b'The organizations in session', related_name='sessions', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='speech',
            name='organization',
            field=models.ForeignKey(blank=True, help_text=b'Organization', null=True, on_delete=django.db.models.deletion.CASCADE, to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='vote',
            name='amendment_of',
            field=models.ManyToManyField(related_name='amendments', through='parlaseje.AmendmentOfOrg', to='parlaskupine.Organization'),
        ),
        migrations.AddField(
            model_name='vote',
            name='amendment_of_person',
            field=models.ManyToManyField(related_name='amendments', to='parlaposlanci.Person'),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='mdt_fk',
            field=models.ForeignKey(blank=True, help_text=b'MDT object', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='parlaskupine.Organization'),
        ),
    ]
