# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0002_auto_20191018_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='law',
            field=models.ForeignKey(blank=True, help_text='Legislation foreign key', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='parlaseje.Legislation'),
        ),
    ]
