# Generated by Django 1.11 on 2019-10-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0003_auto_20191024_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislation',
            name='mdt',
            field=models.CharField(blank=True, help_text=b'Working body', max_length=1024, null=True),
        ),
    ]
