# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0045_vote_amendment_of_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='the_order',
            field=models.IntegerField(blank=True, db_index=True, help_text=b'Absolute order on session', null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='result',
            field=models.CharField(blank=True, choices=[(None, b'Prazno'), (b'accepted', b'sprejet'), (b'rejected', b'zavrnjen')], help_text=b'result of law', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='legislation',
            name='status',
            field=models.CharField(blank=True, choices=[(b'under_consideration', b'v obravnavi'), (b'end_of_hearing', b'konec obravnave')], default=b'under_consideration', help_text=b'result of law', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, help_text='Session name', max_length=512, null=True, verbose_name='name'),
        ),
    ]
