# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 17:36
from __future__ import unicode_literals

from django.db import migrations, models

def forward(apps, schema_editor):
    Activity = apps.get_model("parlaseje", "Activity")
    Question = apps.get_model("parlaseje", "Question")
    for activity in Activity.objects.all():
    	if activity.person:
        	activity.persons.add(activity.person)

    for question in Question.objects.all():
        if question.author_org:
        	question.author_orgs.add(question.author_org)


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0047_auto_20180829_1736'),
    ]

    operations = [
    	migrations.RunPython(forward)
    ]
