# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0048_auto_20180829_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='person',
        ),
    ]
