# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0049_remove_activity_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='persons',
            new_name='person',
        ),
    ]
