# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parlaskupine', '0031_auto_20180820_1140'),
        ('parlaseje', '0050_auto_20180830_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmendmentOfOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='creation time')),
                ('updated_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='last modification time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlaskupine.Organization')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parlaseje.Vote')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
