# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parlaseje', '0051_amendmentoforg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='amendment_of',
        ),
    ]
